### ISSUE TITLE
Error on 'index_type'. Please help me :(

### ISSUE THREAD

**Issue by sugiantonehemia** [ildoonet/deepface#11]
I ran this code "python bin/face.py run --visualize=true --image=samples/blackpink/blackpink1.jpg" and i got this error. Don't know what the actual error is. Could you please help me? Did I miss something here?

```
C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-07-31 16:01:38.664871: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
2018-07-31 16:01:38.962453: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1030] Found device 0 with properties:
name: Quadro K600 major: 3 minor: 0 memoryClockRate(GHz): 0.8755
pciBusID: 0000:04:00.0
totalMemory: 1.00GiB freeMemory: 839.71MiB
2018-07-31 16:01:38.969785: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Quadro K600, pci bus id: 0000:04:00.0, compute capability: 3.0)
2018-07-31 16:01:42.282739: I C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Quadro K600, pci bus id: 0000:04:00.0, compute capability: 3.0)
2018-07-31 16:01:47.795371: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'index_type' not in Op<name=Fill; signature=dims:int32, value:T -> output:T; attr=T:type>; NodeDef: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta)]]
2018-07-31 16:01:47.884747: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'index_type' not in Op<name=Fill; signature=dims:int32, value:T -> output:T; attr=T:type>; NodeDef: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta)]]
2018-07-31 16:01:47.967375: E C:\tf_jenkins\home\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\executor.cc:643] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'index_type' not in Op<name=Fill; signature=dims:int32, value:T -> output:T; attr=T:type>; NodeDef: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta)]]
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1323, in _do_call
    return fn(*args)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1302, in _run_fn
    status, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'index_type' not in Op<name=Fill; signature=dims:int32, value:T -> output:T; attr=T:type>; NodeDef: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/face.py", line 335, in <module>
    fire.Fire(DeepFace)
  File "C:\Anaconda3\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Anaconda3\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Anaconda3\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "bin/face.py", line 137, in run
    faces = self.detector.detect(npimg)
  File "C:\xampp\htdocs\gca_fer\deepface-master\deepface\detectors\detector_ssd.py", line 61, in detect
    self.tensor_image: [infer_img]
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1317, in _do_run
    options, run_metadata)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'index_type' not in Op<name=Fill; signature=dims:int32, value:T -> output:T; attr=T:type>; NodeDef: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta)]]

Caused by op 'prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones', defined at:
  File "bin/face.py", line 335, in <module>
    fire.Fire(DeepFace)
  File "C:\Anaconda3\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Anaconda3\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Anaconda3\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "bin/face.py", line 118, in run
    self.set_detector(detector)
  File "bin/face.py", line 51, in set_detector
    self.detector = FaceDetectorSSDMobilenetV2()
  File "C:\xampp\htdocs\gca_fer\deepface-master\deepface\detectors\detector_ssd.py", line 105, in __init__
    super(FaceDetectorSSDMobilenetV2, self).__init__('ssd_mobilenet_v2')
  File "C:\xampp\htdocs\gca_fer\deepface-master\deepface\detectors\detector_ssd.py", line 24, in __init__
    self.detector = self._load_graph(graph_path)
  File "C:\xampp\htdocs\gca_fer\deepface-master\deepface\detectors\detector_ssd.py", line 51, in _load_graph
    tf.import_graph_def(graph_def, name="prefix")
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\importer.py", line 313, in import_graph_def
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2956, in create_op
    op_def=op_def)
  File "C:\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): NodeDef mentions attr 'index_type' not in Op<name=Fill; signature=dims:int32, value:T -> output:T; attr=T:type>; NodeDef: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
         [[Node: prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones = Fill[T=DT_INT32, index_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](prefix/MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, prefix/Postprocessor/BatchMultiClassNonMaxSuppression/map/TensorArrayUnstack_1/range/delta)]]
```

**Comment by ildoonet** [comment]
Please try again after upgrade your tensorflow to the latest one.
