### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by glennford49** [ildoonet/deepface#17]
command:
/bin$ python run_example.py run --source_path=./samples/blackpink/faces --db_path=./sample_db.pkl --img_path=./samples/blackpink/blackpink1.jpg --method=vgg2

ERROR:

Traceback (most recent call last):
  File "run_example.py", line 51, in <module>
    fire.Fire(DeepFace)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "run_example.py", line 40, in run
    faces = detector.detect(npimg=npimg)
  File "/home/glenn/Downloads/deepface-master/deepface/detectors/detector_ssd.py", line 64, in detect
    height, width = npimg.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by utkarshrai2** [comment]
--source_path=./samples/blackpink/faces
Path is in correct
